### ISSUE TITLE
Hi, any progress with that ?

### ISSUE THREAD

**Issue by borisirota** [egoist/rollup-loader#1]
This is exactly what I'm doing but with different npm scripts. Can be neat to have it all in one config file and call one command.

**Comment by egoist** [comment]
Sorry, in favor of the coming Webpack 2 I think we don't need rollup-loader anymore.

**Comment by Kuznetsov-Ilia** [comment]
Why? Webpack 2 is still quite different tool. Webpack is awesome in development (HMR) and with it`s loaders, but rollup is about merging scopes without wrappers. Rewriting webpack-loaders to rollup plugins is awful way...

**Comment by egoist** [comment]
I just doubt the use cases of using Webpack 2 with `rollup-loader`

**Comment by silentroach** [comment]
so why not remove the package from npm?

**Comment by egoist** [comment]
@silentroach It was impossible to make `rollup-loader` work with webpack, there was no way to exclude things like `.css` files dynamically, but since https://github.com/rollup/rollup/issues/522#issuecomment-224224854 was fixed, it's possible now.

So I am looking into this.

**Comment by gnz00** [comment]
@egoist Since webpack2 is in beta, it would be nice to have tree shaking in Webpack 1. Have you discontinued this initiative and moved on to WP2? Is anyone using WP2 in production?

**Comment by AndyOGo** [comment]
@egoist 
what has been decided now?

**Comment by flying-sheep** [comment]
hmm, webpack 2 still mangles code.

only rollup is able to create a unmangled bundle without `__webpack_require__` or `module.exports`

**Comment by AndyOGo** [comment]
@egoist 
Any feedback, update?

**Comment by egoist** [comment]
Hi all, I'm now using webpack 2 but have no time and use cases to try webpack 2 with rollup rencently, this loader seems to work but definitely some bugs, PRs or transferring it to someone who excels at webpack or rollup is ok ;)

**Comment by dfrankland** [comment]
I've gone ahead and created [`rollup-webpack-loader`](https://www.npmjs.com/package/rollup-webpack-loader). So far it has worked well for my test cases 👍

**Comment by egoist** [comment]
I've updated `rollup-loader` to `v0.1.0`, feel free to open new issues to report bugs or request new features. closed this for now.
