### ISSUE TITLE
What is the gain from using Rollup loader?

### ISSUE THREAD

**Issue by mlunoe** [egoist/rollup-loader#4]
Hi there,

Looking through Rollup and Webpack 2 it seems that Webpack 2 already includes Tree Shaking by default: http://www.2ality.com/2015/12/webpack-tree-shaking.html and https://moduscreate.com/webpack-2-tree-shaking-configuration/

What is the gain from using Rollup?

Cheers

**Comment by egoist** [comment]
https://github.com/egoist/rollup-loader/issues/1 discussions here might be helpful
